# Generated by Django 4.0.5 on 2023-02-05 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'eaterlier_Branch',
            },
        ),
        migrations.CreateModel(
            name='Eatery',
            fields=[
                ('eatery_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Eatery/')),
            ],
            options={
                'db_table': 'eaterlier_Eterly',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('food_category_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='uncategorised', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BranchFoodCategory', to='Hotel.branch')),
            ],
            options={
                'db_table': 'eaterlier_FoodCategory',
            },
        ),
        migrations.CreateModel(
            name='FoodSubCategory',
            fields=[
                ('food_subcategory_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='uncategorised', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FoodSubCategory', to='Hotel.foodcategory')),
            ],
            options={
                'db_table': 'eaterlier_FoodSubCategory',
            },
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('food_product_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='food_products/')),
                ('quantityAvailable', models.PositiveIntegerField()),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.foodsubcategory')),
            ],
            options={
                'db_table': 'eaterlier_FoodProduct',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchREF', to='Hotel.eatery'),
        ),
    ]
