# Generated by Django 4.0.5 on 2023-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatery',
            name='email',
            field=models.CharField(default='admin@email.com', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='eatery',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eatery',
            name='password',
            field=models.TextField(default='password', max_length=200, verbose_name='Password'),
        ),
    ]
